### PR TITLE
Add Posix Message Queue demo

### PR DESCRIPTION
**Pull request by antonio-pedro99**
I have just added the Posix Message Queue demo since this repo only contains a demo for the **System V** Message queue demo.

### CODE REVIEW

**Review by shake0 — COMMENTED** [review]
Hey Antonio! Thank you very much for you PR. Can you please remove the binary files p1, p2 ?

**Comment by antonio-pedro99** [comment]
For sure/

**Comment by antonio-pedro99** [comment]
Done.

**Comment by antonio-pedro99** [comment]
Thanks Sir.

**Pull request merged**
